Intento 3

diff --git a/.github/workflows/deploy-glue.yml b/.github/workflows/deploy-glue.yml
--- a/.github/workflows/deploy-glue.yml
+++ b/.github/workflows/deploy-glue.yml
@@ -20,11 +20,16 @@ jobs:
 
       - name: Cargar variables del Glue Job
         run: |
-          cd test_glue
-          source test_glue/glue_config.env
-          echo "JOB_NAME=$JOB_NAME" >> $GITHUB_ENV
-          echo "SCRIPT_LOCATION=$SCRIPT_LOCATION" >> $GITHUB_ENV
-          echo "ROL_ARN=$ROL_ARN" >> $GITHUB_ENV
+          if [ -d "test_glue" ]; then
+            cd test_glue
+            source glue_config.env
+            echo "JOB_NAME=$JOB_NAME" >> $GITHUB_ENV
+            echo "SCRIPT_LOCATION=$SCRIPT_LOCATION" >> $GITHUB_ENV
+            echo "ROL_ARN=$ROL_ARN" >> $GITHUB_ENV
+          else
+            echo "Error: Directory 'test_glue' does not exist."
+            exit 1
+          fi
 
 
       - name: Configurar AWS credenciales via OIDC
